### PR TITLE
Add Core/Array/array_column. Fixes #8

### LINKED ISSUE #8: Core/Array/array_column

### PR DESCRIPTION
**Pull request by ddziaduch**

### CODE REVIEW

**Review by nkkollaw — CHANGES_REQUESTED** [review]
I think the test is wrong. It "checks itself".

`$actual` should be `\Zubr\array_column`, `$expected` `\array_column`.

Can you check?

**Comment by ddziaduch** [comment]
Haha you are right! I will fix this today :)

**Comment by nkkollaw** [comment]
Yup, no problem :-)

**Comment by ddziaduch** [comment]
@nkkollaw it's done

**Review by nkkollaw — APPROVED** [review]

**Comment by nkkollaw** [comment]
Good job, @ddziaduch .

**Pull request merged**
